spring.application.name=deardiary
# Database
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/deardiary_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:Pragna@955}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# JWT
jwt.secret=${JWT_SECRET:deardiary_super_secret_signing_key_for_jwt_tokens_2026_secure}
jwt.expiration=86400000
# Server
server.port=${PORT:8082}
logging.level.org.springframework.security=DEBUG